---
title: "homework4_gii"
author: "Jin Jiang"
date: "2022-11-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(sf)
library(here)
library(janitor)
library(tidyverse)
library(dplyr)
library(countrycode)
library(tmap)
library(tmaptools)
```
read in data
```{r}

# read the files based on local path
# read the spatial data and clean column names
world_countries <- st_read(here::here("prac4_data",
                                  "World_Countries_(Generalized)",
                                      "World_Countries__Generalized_.shp")) %>%
  clean_names()

# read the global gender inequality data
indices_all <- read_csv(here::here("prac4_data",
"HDR21-22_Composite_indices_complete_time_series.csv"), locale = locale(encoding = "latin1"),
na = "", skip=0)


```

```{r}
# Since the spatial data includes the outside
#  overseas territory, change the country name
# in the csv to iso_code and join the spatial data

csv_diff_gii <- indices_all %>%
  # calculate the difference of gii 
  mutate(diff_gii = gii_2019 - gii_2010) %>%
  # use countrycode pkg to change country name
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))%>%
  # select the required columns from csv2
  dplyr::select("diff_gii","iso_code", "gii_2019","gii_2010","country")
  
```

```{r}
# join csv data to country shapefile
countries_gii_join <- world_countries %>%
  dplyr::left_join(., csv_diff_gii, by = c("iso"="iso_code"))
```

mapping

```{r}
# quick map
qtm(countries_gii_join, fill = "diff_gii")
```


```{r}
# advanced map
tmap_mode("plot")

tm_shape(countries_gii_join) + 
  tm_polygons("diff_gii", 
        style="jenks",
        palette="YlOrBr",
        midpoint=NA,
        title="GII difference",
        alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Difference in Gender Inequality Index 2010-2019", legend.position = c("right", "bottom"))
```

